[package]
name = "todo"
version = "0.1.0"
authors = ["Pietro Bongiovanni <pietro.bongiovanni@mollie.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rusqlite = "0.24.0"
